### PR TITLE
Examples webpack work

### PR DESCRIPTION
**Pull request by igorschoester**
## Summary

This PR can be summarized in the following changelog entry:

* N/A

## Relevant technical choices:

- Fixed some spacing irregularities with the paper UI, columns and inputs.
- Fixed Jed error from `yoast-components`.
- Fixed `locale` not being saved to the configuration.
- Added webpack alias to the `YoastSEO.js` `src` folder.
- Added `ButtonContainer`, `HeadingContainer` and `HorizontalContainer`.
- Added `fullTestTexts`'s papers as input with the help of `react-select`.
- Added overall scores.
- Changed raw markings: moved inside a collapsible to save screen space.
- Changed control buttons to `yoast-components`'s `IconButton`.
- Changed `StatusBox` to use flexbox.
- Removed TypeScript loader.
- Removed the H1, this is not an actual web page; it took up valuable screen space.

## Test instructions

This PR can be tested by following these steps:

* Go to `examples/webpack`.
* Install dependencies: `yarn`.
* Run it: `yarn start`.
* Check out the changes (see the list in the choices section).
* Ensure other things are still functioning properly.

### CODE REVIEW

**Comment by nataliashitova** [comment]
Acceptance (WIP):

- [ ] Fixed some spacing irregularities with the paper UI, columns and inputs.
- [ ] Fixed Jed error from yoast-components.
- [ ] Fixed locale not being saved to the configuration.
- [ ] Added webpack alias to the YoastSEO.js src folder.
- [ ] Added ButtonContainer, HeadingContainer and HorizontalContainer.
- [ ] Added fullTestTexts's papers as input with the help of react-select.
- [ ] Added overall scores.
- [ ] Changed raw markings: moved inside a collapsible to save screen space.
- [ ] Changed control buttons to yoast-components's IconButton.
- [ ] Changed StatusBox to use flexbox.
- [ ] Removed TypeScript loader.
- [ ] Removed the H1, this is not an actual web page; it took up valuable screen space.

**Comment by igorschoester** [comment]
Changed things again 😅 

- Fixed good result icon color to match the plugin color.
- Fixed the Jed error -- hopefully 😉

**Comment by hansjovis** [comment]
Acceptance test: 🔶 .

Everything works, but it would be nice to have the test paper select element reflect the selected paper. Now it keeps showing `Select...`.

For this I think it will be better to make `SelectTestPaper` into a class, instead of a function.

**Comment by hansjovis** [comment]
Loading will probably fail completely if #1973 is merged, since it uses a `node` function to load the html-text from disk (instead of the html-text being inside of the test files themselves).

**Comment by igorschoester** [comment]
> Everything works, but it would be nice to have the test paper select element reflect the selected paper. Now it keeps showing `Select...`.
> 
> For this I think it will be better to make `SelectTestPaper` into a class, instead of a function. 

I view it more as a one time copy over the test paper values to the inputs. To make it perfect you would also have to listen to all the inputs and compare them to the test paper values. That seems overkill.
Before, it had the behavior of keeping the paper there until you refresh. But I thought that was confusing so I made it so it always shows `Select...`.


> Loading full paper texts will probably fail completely if #1973 is merged, since it uses a node function to load the html-text from disk (instead of the html-text being inside of the test files themselves).

This should be fixed in that PR then? 🙃

**Pull request merged**
