### PR TITLE
Add Catalan transition words

### LINKED ISSUE #1484: Add transition word assessment for Catalan
We should add the transition word assessment for Catalan.

### PR DESCRIPTION
**Pull request by agnieszkaszuba**
## Summary

This PR can be summarized in the following changelog entry:

* Adds transition words for Catalan 

## Relevant technical choices

* Specifically addresses a question of transition words with apostrophes. 

## Test instructions

This PR can be tested by following these steps:

### Browserified

- check out the branch
- use the browserfied example. Don't forget to run a grunt build:js
- Set locale to ca_ES
- Write a Catalan sentence containing a one or two-part transition word (see list of transition words in the code files)
- Hit the mark transition word sentences button to check if the sentences are correctly marked.

### WordPress

- In your WordPress SEO testing environment, ensure you've already run yarn install once in the plugin's directory.
- Run yarn add "git+https://github.com/Yoast/yoastseo.js#stories/1484-add-transition-words-catalan" in the plugin's directory.
- Navigate to node_modules/yoastseo and run yarn install and grunt build:js.
- Navigate back to the plugin's directory and run grunt build:js.
- In your testing environment, set the language to Catalan ("ca").
- Write a Catalan text.
- Determine that the transition word assessments appears in the list and no error occur.

Fixes #1484

### CODE REVIEW

**Comment by manuelaugustin** [comment]
CR done 👍

**Comment by Dieterrr** [comment]
Tested commit both in Browserfied as well as in Wordpress environment. Results were the same. 
Used google translate to get Catalan sentences with transition words. 

See results below. Some sentences with transition words worked perfectly some didn't. I know results here cannot be perfect so I think it's good to have a second opinion. I feel it's a bit strange that pretty basic transition words like **and, before & next** fail. But perhaps there is a technical reason for this or maybe the google translation is incorrect? 

`The little girl put on her yellow shirt **and** brown overalls.
La noia va posar la seva camisa groga i els micos marrons.`
—> 0% transition word, false

`Chris is on the basketball team this semester at Indiana School for the Deaf. **In addition**, he is on the soccer team.
Chris és a l'equip de bàsquet aquest semestre a l'Indiana School for the Sord. A més, és a l'equip de futbol.`
—> 50%, correct

`**First** of all, pour a half-cup of milk in the bowl; **second**, add two eggs; and **third**, stir the mixture.
En primer lloc, aboqui una mitja tassa de llet al plat; En segon lloc, afegiu dos ous; i en tercer lloc, remoure la barreja.`
—> 100%, correct

Crystal likes camping in the mountains. **Also**, Crystal is an experienced hiker.
Crystal li agrada acampar a les muntanyes. A més, Crystal és un excursionista experimentat.
—> 50%, correct. 

`Stephen went to pick up Irene **before** he stopped by McDonald's for lunch.
Stephen va anar a recollir Irene abans que es va aturar per McDonald's per dinar.`
—> 0% transition word, false. 

`Clerc met with Gallaudet to prepare for the Congressional meeting scheduled for the **next** day.
Clerc es va reunir amb Gallaudet per preparar-se per a la reunió del Congrés prevista per al dia següent.`
—> 0% transition word, false.

**Comment by manuelaugustin** [comment]
"A més" is actually on our list, so it should have been recognized. For the other ones we'll have to check whether it makes sense to include them. @agnieszkaszuba can you have a look at that on Friday?

**Comment by agnieszkaszuba** [comment]
@manuelaugustin I think "a més" works fine in the examples that Dieter gave, it is 50 % because there are two sentences.

We haven't included "and" in any transition words lists, including Catalan. I'm not sure why, but I think it makes the bar for transition words pretty low?

I missed "before", I will add it to the list. 

"seguënt" is not on the list, but several other words that translate to 'next' are (e.g. "a continuación", "tot seguit"). Those are used in more 'transitiony' contexts, like "Next, add sugar." = "A continuación, afegiu sucre". I wouldn't consider 'next' in an adjectival phrase like 'next day' a transition word, personally. And I checked the lists for other languages, it seems like we did not include such sense of the word 'next' in those lists either.

**Comment by manuelaugustin** [comment]
CR done 👍

**Comment by Dieterrr** [comment]
Acceptance 👍

**Comment by Dieterrr** [comment]
Build in combination with either Wordpress-seo-free Trunk or Master fails with the following errors:
```
Module not found: Error: Can't resolve 'yoastseo/js/helpers/createMeasurementElement' in '/Users/dieterschalk/Code/Yoast/Wiki/yoast-cli/tmp/js/src/analy  
  sis'                                                                                                                                                      
   @ ./js/src/analysis/PostDataCollector.js 25:32-87                                                                                                        
   @ ./js/src/wp-seo-post-scraper.js                                                                                                              
                                                                                                                                                            
  ERROR in ./js/src/analysis/TermDataCollector.js                                                                                                  
  Module not found: Error: Can't resolve 'yoastseo/js/helpers/createMeasurementElement' in '/Users/dieterschalk/Code/Yoast/Wiki/yoast-cli/tmp/js/src/analy  
  sis'                                                                                                                                                      
   @ ./js/src/analysis/TermDataCollector.js 31:32-87                                                                                                        
   @ ./js/src/wp-seo-term-scraper.js                                                                                                              
  Warning:  Use --force to continue.                                                                                                                       
                                                                                                                                                            
  Aborted due to warnings.
```

**Comment by Dieterrr** [comment]
Build now passes, and everything works as it should in the acceptance test! 👍

**Pull request merged**
