### PR TITLE
Update the preprocessor to fix wordcount

### LINKED ISSUE #124: Page analysis: word count is inaccurate
The word count of the page analysis is inaccurate when the content contains certain values.

The page analysis tells me that the text contains:
- 2 words when the content contains only one word (with or without whitespace).
    (the word count is only one off if it is calculated by the client side javascript. It shows the right amount after a refresh). e.g. "Word"
- 1 word (I expect 0 words once the point mentioned above is fixed) when entering a number followed by 2 spaces, dashes or commas. e.g. "12  "
- 3 words when entering a letter or word followed by two spaces. e.g. "Word  "

This issue occurs when creating and editing Post, Pages and Locations (Local SEO).

Using:
- Wordpress version 4.3.1
- Yoast SEO (branch 3.0) using all default setttings
- Google chrome

Other active plugins and themes:
- Local SEO for Yoast SEO (1.3.8)
- WordPress SEO News (2.2.5)
- Twenty Fifteen

### PR DESCRIPTION
**Pull request by terw-dan**
Fixes #124
Improves the regex in the stripspaces functions, to make sure all duplicate spaces are stripped correctly, so the wordcount is accurate, this was not always the case. 

Also Fixes #https://github.com/Yoast/wordpress-seo/issues/3154

### CODE REVIEW

**Comment by atimmer** [comment]
This needs unit tests, see #124 for the different cases

**Comment by CarolineGeven** [comment]
# Acceptance
Not yet fixed.

**Comment by atimmer** [comment]
CR Done 👍🏻

**Comment by CarolineGeven** [comment]
Acceptance done

**Pull request merged**
