### PR TITLE
Recalibrate text images

### LINKED ISSUE #1938: Images keyphrase: check how many matches there are
Currently we give a green bullet when at least one image has an alt text with the keyword.

The boundaries of this check should change. The check should be triggered when there are ≥5 images. The boundaries can be the same as for the keyword in subheadings assessment (min 30, max 75%).

For more context/a previous implementation of this, see https://github.com/Yoast/YoastSEO.js/issues/1388 (+ related PR).

### PR DESCRIPTION
**Pull request by nataliashitova**
## Summary

This PR can be summarized in the following changelog entry:

* Implements a recalibrated version of the assessment that checks whether the keyphrase is used in the alt-tags of images, so that if more than 4 images are added to the article, between 30 and 70% of them contain the keyphrase.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

###  Regular analysis
* Start a regular analysis example `yarn start`
* Add a text without images > Red: `Image alt attributes: No images appear on this page. Add some!`
* Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Add an alt-tag with some text > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Set a keyphrase and repeat the previous three tests > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Use a 1-word keyphrase and add this word to the alt-tag > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* Add 2 more (content) words to the keyphrase without changing the alt-tag > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* Copy the image and paste it 5 more times. > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* Remove alt-tags in all images but one > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* Remove alt-tags in the last image > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
###  Recalibration analysis
* Start a regular analysis example `yarn start-recalibration`
* Add a text without images > Red: `Image alt attributes: No images appear on this page. Add some!`
* Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Add an alt-tag with some text > Orange `Image alt attributes: Images on this page have alt attributes, but you have not set your keyphrase. Fix that!`
* Set a keyphrase
* Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* Add an alt-tag with some text > Orange `Image alt attributes: Images on this page do not have alt attributes with at least half of the words from your keyphrase. Fix that!`
* Use a 1-word keyphrase and add this word to the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* Add 1 more (content) word to the keyphrase without changing the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* Add 1 more (content) word to the keyphrase without changing the alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with at least half of the words from your keyphrase. Fix that!`
* Duplicate the image and use the at least half of the keyphrase words in one of alt-tags, but not in the other. > Green `Image alt attributes: Out of 2 images on this page, 1 has an alt attribute with at least half of the words from the keyphrase. Good job!`
* Duplicate the images. > Green `Image alt attributes: Out of 4 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* Add one more image with or without an alt-tag. > Green `Image alt attributes: Out of 5 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* Remove the alt-tag on one of the images where two words from the keyphrase were matched > Orange `Image alt attributes: Out of 5 images on this page, only 1 has an alt attribute with at least half of the words from your keyphrase. Fix that!`
* Add alt-tags with keyphrase words to 4 out of 5 images. > Green `Image alt attributes: Out of 5 images on this page, 4 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* Add alt-tags with keyphrase words to the 5th image. > Orange `Image alt attributes: Out of 5 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* Add one more image without an alt-tag. > Orange `Image alt attributes: Out of 6 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* Add one more image with an alt-tag that does not contain half of the words from the keyphrase. > Green `Image alt attributes: Out of 7 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. Good job!`
* Remove alt-tags or keyphrase words from the alt-tags of 3 images > Orange `Image alt attributes: Out of 7 images on this page, only 2 have alt attributes with at least half of the words from your keyphrase. Fix that!`

 
Fixes #1938

### CODE REVIEW

**Comment by hansjovis** [comment]
Acceptance test: _in progress_

###  Regular analysis
* [x] Add a text without images > Red: `Image alt attributes: No images appear on this page. Add some!`
* [x] Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [x] Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an alt-tag with some text > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Set a keyphrase and repeat the previous three tests > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Use a 1-word keyphrase and add this word to the alt-tag > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Add 2 more (content) words to the keyphrase without changing the alt-tag > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Copy the image and paste it 5 more times. > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Remove alt-tags in all images but one > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Remove alt-tags in the last image > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
###  Recalibration analysis
* [ ] Add a text without images > Red: `Image alt attributes: No images appear on this page. Add some!`
* [ ] Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an alt-tag with some text > Orange `Image alt attributes: Images on this page have alt attributes, but you have not set your keyphrase. Fix that!`
* Set a keyphrase
* [ ] Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an alt-tag with some text > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Use a 1-word keyphrase and add this word to the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add 1 more (content) word to the keyphrase without changing the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add 1 more (content) word to the keyphrase without changing the alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with at least half of the words from your keyphrase. Fix that!`
* [ ] Duplicate the image and use the at least half of the keyphrase words in one of alt-tags, but not in the other. > Green `Image alt attributes: Out of 2 images on this page, 1 has an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Duplicate the images. > Green `Image alt attributes: Out of 4 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add one more image with or without an alt-tag. > Green `Image alt attributes: Out of 5 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Remove the alt-tag on one of the images where two words from the keyphrase were matched > Orange `Image alt attributes: Out of 5 images on this page, only 1 has an alt attribute with at least half of the words from your keyphrase. Fix that!`
* [ ] Add alt-tags with keyphrase words to 4 out of 5 images. > Green `Image alt attributes: Out of 5 images on this page, 4 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add alt-tags with keyphrase words to the 5th image. > Orange `Image alt attributes: Out of 5 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* [ ] Add one more image without an alt-tag. > Orange `Image alt attributes: Out of 6 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* [ ] Add one more image with an alt-tag that does not contain half of the words from the keyphrase. > Green `Image alt attributes: Out of 7 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. Good job!`
* [ ] Remove alt-tags or keyphrase words from the alt-tags of 3 images > Orange `Image alt attributes: Out of 7 images on this page, only 2 have alt attributes with at least half of the words from your keyphrase. Fix that!`

**Comment by nataliashitova** [comment]
@hansjovis Indeed wrong test instructions 😞 
I fixed the error and checked all the other ones.

**Comment by hansjovis** [comment]
> @hansjovis Indeed wrong test instructions 😞
> I fixed the error and checked all the other ones.

Okay! 🙂 .

**Comment by igorschoester** [comment]
###  Regular analysis
* [x] Add a text without images > Red: `Image alt attributes: No images appear on this page. Add some!`
* [x] Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [x] Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [x] Add an alt-tag with some text > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Set a keyphrase and repeat the previous three tests > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Use a 1-word keyphrase and add this word to the alt-tag > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Add 2 more (content) words to the keyphrase without changing the alt-tag > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Copy the image and paste it 5 more times. > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Remove alt-tags in all images but one > Green `Image alt attributes: Some images on this page contain alt attributes with words from your keyphrase! Good job!`
* [ ] Remove alt-tags in the last image > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
###  Recalibration analysis
* [ ] Start a regular analysis example `yarn start-recalibration`
* [ ] Add a text without images > Red: `Image alt attributes: No images appear on this page. Add some!`
* [ ] Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an alt-tag with some text > Orange `Image alt attributes: Images on this page have alt attributes, but you have not set your keyphrase. Fix that!`
* [ ] Add an image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Add an alt-tag with some text > Orange `Image alt attributes: Images on this page do not have alt attributes with at least half of the words from your keyphrase. Fix that!`
* [ ] Use a 1-word keyphrase and add this word to the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add 1 more (content) word to the keyphrase without changing the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add 1 more (content) word to the keyphrase without changing the alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with at least half of the words from your keyphrase. Fix that!`
* [ ] Duplicate the image and use the at least half of the keyphrase words in one of alt-tags, but not in the other. > Green `Image alt attributes: Out of 2 images on this page, 1 has an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Duplicate the images. > Green `Image alt attributes: Out of 4 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add one more image with or without an alt-tag. > Green `Image alt attributes: Out of 5 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Remove the alt-tag on one of the images where two words from the keyphrase were matched > Orange `Image alt attributes: Out of 5 images on this page, only 1 has an alt attribute with at least half of the words from your keyphrase. Fix that!`
* [ ] Add alt-tags with keyphrase words to 4 out of 5 images. > Green `Image alt attributes: Out of 5 images on this page, 4 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add alt-tags with keyphrase words to the 5th image. > Orange `Image alt attributes: Out of 5 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* [ ] Add one more image without an alt-tag. > Orange `Image alt attributes: Out of 6 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* [ ] Add one more image with an alt-tag that does not contain half of the words from the keyphrase. > Green `Image alt attributes: Out of 7 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. Good job!`
* [ ] Remove alt-tags or keyphrase words from the alt-tags of 3 images > Orange `Image alt attributes: Out of 7 images on this page, only 2 have alt attributes with at least half of the words from your keyphrase. Fix that!`

**Comment by igorschoester** [comment]
Acceptance 🚧 

- Without recalibration. With an image. With an alt-tag. With 1 word from the keyphrase.
screen shot 2018-11-07 at 10 54 38

- Same feedback with 6 images.
- Same feedback with 6 images. One with 1 word from the keyphrase, 5 without an alt-tag.

**Comment by manuelaugustin** [comment]
I've made some changes to the feedback strings. These changes still need to be reviewed and then an acceptance test of the recalibration test should be done (I've already acceptance-tested the non-recalibration part).

**Comment by hansjovis** [comment]
## Acceptance Test: [WIP]
Since @manuelaugustin already tested the non-recalibration part, I will only test the recalibration part.

###  Recalibration analysis
* [ ] Text without images > Red: `Image alt attributes: No images appear on this page. Add some!`
* [ ] Text with 1 image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Text with 1 image with an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Text with 1 image with an alt-tag with some text > Orange `Image alt attributes: Images on this page have alt attributes, but you have not set your keyphrase. Fix that!`
* [ ] Text with 1 image without alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Text with 1 image with an empty alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with words from your keyphrase. Fix that!`
* [ ] Text with 1 image with an alt-tag with some text > Orange `Image alt attributes: Images on this page do not have alt attributes with at least half of the words from your keyphrase. Fix that!`
* [ ] Use a 1-word keyphrase and add this word to the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add 1 more (content) word to the keyphrase without changing the alt-tag > Green `Image alt attributes: The image on this page contains an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add 1 more (content) word to the keyphrase without changing the alt-tag > Orange `Image alt attributes: Images on this page do not have alt attributes with at least half of the words from your keyphrase. Fix that!`
* [ ] Duplicate the image and use the at least half of the keyphrase words in one of alt-tags, but not in the other. > Green `Image alt attributes: Out of 2 images on this page, 1 has an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Duplicate the images. > Green `Image alt attributes: Out of 4 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add one more image with or without an alt-tag. > Green `Image alt attributes: Out of 5 images on this page, 2 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Remove the alt-tag on one of the images where two words from the keyphrase were matched > Orange `Image alt attributes: Out of 5 images on this page, only 1 has an alt attribute with at least half of the words from your keyphrase. Fix that!`
* [ ] Add alt-tags with keyphrase words to 4 out of 5 images. > Green `Image alt attributes: Out of 5 images on this page, 4 have an alt attribute with at least half of the words from the keyphrase. Good job!`
* [ ] Add alt-tags with keyphrase words to the 5th image. > Orange `Image alt attributes: Out of 5 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* [ ] Add one more image without an alt-tag. > Orange `Image alt attributes: Out of 6 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. That's a bit much. Only include the focus keyphrase when it really fits the image.`
* [ ] Add one more image with an alt-tag that does not contain half of the words from the keyphrase. > Green `Image alt attributes: Out of 7 images on this page, 5 have alt attributes with at least half of the words from the keyphrase. Good job!`
* [ ] Remove alt-tags or keyphrase words from the alt-tags of 3 images > Orange `Image alt attributes: Out of 7 images on this page, only 2 have alt attributes with at least half of the words from your keyphrase. Fix that!`

**Pull request merged**
