### PR TITLE
Keyworddensity Assessment

### LINKED ISSUE #330: Create assessment for keywordensity
create an assement for the keyworddensity

### PR DESCRIPTION
**Pull request by terw-dan**
Adds keyword density assessment and updates specs.

Fixes #330

### CODE REVIEW

**Comment by andizer** [comment]
CR done.

**Comment by jcomack** [comment]
Acceptance done.

The keyword density never shows up in the list. I think something is broken / missing somewhere.
Also, keyword density are two separate words, so you might want to update some of the docs as well.

**Comment by terw-dan** [comment]
Fixed merge. 
For acceptance: The keyword density shows up with 100+ words in the examplescraper

**Comment by andizer** [comment]
Cr done.

**Comment by jcomack** [comment]
Assessment done :+1:

**Pull request merged**
