### PR TITLE
Adapt transition word assessment for French and Spanish.

### LINKED ISSUE #762: Add transition word assessment for Spanish and French
We should make the transition word assessment available for Spanish and French.

### PR DESCRIPTION
**Pull request by IreneStr**
Adapts transition word assessment for French and Spanish.

Fixes #762 

For testing: change locale to es_ES and fr_FR. Write sentences with and without one-part and two-part transition words. 

Examples French:
- one-part: en général, cela dit, en somme.
- two-part: tantôt...tantôt, si...que.

Examples Spanish: 
- one-part: en primera instancia, a pesar de eso, tal como.
- two-part: de un lado...de otro, no...sino que.

### CODE REVIEW

**Comment by terw-dan** [comment]
CR Done :+1:

**Comment by boblinthorst** [comment]
Acceptance ok 👍

**Comment by tanirivera** [comment]
Hello. I'm totally new here, and I have some additions to the Spanish transition words. Could you please tell me what to do? Is there any way I could add them to the files? Thank you.

**Comment by IreneStr** [comment]
@tanirivera Thank you for contributing! There are two options: you could either list them in a [new issue](https://github.com/Yoast/YoastSEO.js/issues/new), or create a pull request on the Spanish transition word list.

**Comment by tanirivera** [comment]
Thank you @IreneStr 
I added the list as a NEW ISSUE [in here](https://github.com/Yoast/YoastSEO.js/issues/861).

**Pull request merged**
