### PR TITLE
Make class for yoast-section.

### PR DESCRIPTION
**Pull request by andizer**
Change the id based styling into class based.

### CODE REVIEW

**Comment by terw-dan** [comment]
CR done 👍

**Comment by terw-dan** [comment]
Acceptance, when using this PR the snippet preview the snippet preview has no longer a maximum width of ~600 px. 

image

We should keep the snippet preview the same width as it had before.

**Comment by andizer** [comment]
@rensw90 Why did you set this pull to scheduled without giving feedback?

**Comment by rensw90** [comment]
Because of the note from @terw-dan about this PR that has to be addressed.

**Comment by andizer** [comment]
@rensw90 If you take  As far as I know, the styling issue should be gone by doing `grunt build:jst` and that file is committed already by @terw-dan

**Comment by terw-dan** [comment]
@andizer @rensw90 
The last thing that went wrong was the missing border-box in the CSS. I've added that, so please review and test.

**Comment by rensw90** [comment]
Acceptance done 👍

**Pull request merged**
