### PR TITLE
Updates subheading length formula

### LINKED ISSUE #469: We should update the formula used for the subheading length assessment
We should update the formula used for the subheading length assessment for consistency.

Old formula:
9 - Math.max( Math.min( ( 4 / 9 ) * ( characters - 25.5 ), 6 ), 0 )

New formula:
9 - Math.max( Math.min( ( 6 / 20 ) * ( characters - 23.4 ), 6 ), 0 )

### PR DESCRIPTION
**Pull request by IreneStr**
Updates subheading length formula
Adds floating point fix to score

Fixes #469

### CODE REVIEW

**Comment by jcomack** [comment]
CR done 👍

**Comment by jcomack** [comment]
Acceptance done.

Adding empty subheadings is considered "good". Doesn't seem like intended behaviour.

**Comment by terw-dan** [comment]
CR Done :+1:

**Comment by terw-dan** [comment]
Acceptance: With no subheadings, it returns a grey bullet with the message that 0% of the subheadings contain more than 30 characters. 
If no subheadings, we should ommit these.

**Comment by andizer** [comment]
CR done.

**Pull request merged**
