### PR TITLE
Fix automatic meta description generation

### PR DESCRIPTION
**Pull request by atimmer**
The automatic meta description generation based on the focus keyword was
broken on trunk. This fixes it.

### CODE REVIEW

**Comment by omarreiss** [comment]
When I choose a focus keyword that doesn't occur in the text, the metadescription becomes empty.

**Comment by omarreiss** [comment]
The current matching is case sensitive. When I have "Avocado" as my focus kw, it will not match the phrase "Everybody loves avocado"

**Comment by omarreiss** [comment]
CR :-1:

**Comment by jcomack** [comment]
Had to delete the code below as it resulted in a permanent loop.
Posting this as a possible back up example of how things used to be.

```
// Generate a meta description based on where in the text the keyword is found first
	if ( this.refObj.rawData.keyword !== "" && this.refObj.rawData.text !== "" ) {
		var curStart = 0;
		var indexMatches = this.getIndexMatches();
		var periodMatches = this.getPeriodMatches();

		metaText = metaText.substring( 0, analyzerConfig.maxMeta );

		if ( indexMatches.length > 0 ) {
			var j = 0;

			while ( j < periodMatches.length ) {
				if ( periodMatches[ 0 ] < indexMatches[ 0 ] ) {
					curStart = periodMatches.shift();
				} else if ( curStart > 0 ) {
					curStart += 2;
				} else {
					break;
				}
			}
		}
	}
```

**Comment by atimmer** [comment]
Closed in favor of #387

**Pull request closed without merging**
