### PR TITLE
Change page title to snippet title

### LINKED ISSUE #120: Confusing which page title I have to change
When I enter a titel for my post, the snippet preview takes this title also, which is nice. But the text analysis is giving the following message:
edit_page_ _theme_ _wordpress

So I changed my page title to improve my post. But the message is still there. Only when I change the title in the snippet preview the line will go away. For me `page title` is confusing, it would be better to reference to the snippet title.

### PR DESCRIPTION
**Pull request by manuelaugustin**
## Summary

This PR can be summarized in the following changelog entry:
Change "page title" to "snippet title" in the snippet title feedback string.

Fixes #120

### CODE REVIEW

**Comment by CarolineGeven** [comment]
I'm unsure if this is the solution we want. `snippet title` is more clear than `page title` when the user edited the snippet title. But when a user does not edit the snippet title, but his page title, we copy the page title to the snippet title. Any edits to the title, would be done from the page title field, not from the snippet title. I'm not sure if changing `page title` to `snippet title` solves this. Perhaps we need to check when the snippet title is edited and when we use the page title as snippet title.

@hedgefield and @moorscode could you please look at this from the UX point of view and come with a suggestion?

**Comment by hedgefield** [comment]
@CarolineGeven that makes sense to me, if we change the warning based on where the edit was made/which field currently has priority for SEO. Could we also include a link with an anchor on either field, so users can jump straight to the one they need?

**Comment by moorscode** [comment]
We are referring to it as `SEO title` instead of `snippet` or `page` title. Which gives a more generalized approach.

The SEO title can be adjust by modifying the page title or the snippet title.

Please change accordingly.

**Comment by CarolineGeven** [comment]
CR and acceptance done 👍

**Pull request merged**
